-- DROP DATABASE users;
-- CREATE DATABASE sipols;
-- USE sipols;

-- CREATE TABLE users (
	-- id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	-- username VARCHAR(12) NOT NULL,
	-- pass VARCHAR(50) NOT NULL 
-- );

CREATE TABLE stars (
	id INT KEY NOT NULL AUTO_INCREMENT,
	image VARCHAR(255) NOT NULL, 
	user_id INT  NOT NULL 
);